language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/travis/.sonar/cache
  - $HOME/travis/.sonarscanner/
  - $HOME/.sonarscanner/sonar-scanner-2.8
sudo: false
install: true
script:
  mvn sonar:sonar \
  -Dsonar.organization=pp2-2018 \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=13b4e313aebcb964109f8b5e6deaaaaf3f1a5454
  
after_success:
  - mvn clean test jacoco:report coveralls:report     
  
  
email:
    on_success: never # default: change
    on_failure: always # default: always