language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/travis/.sonar/cache
  - $HOME/travis/.sonarscanner/
  - $HOME/.sonarscanner/sonar-scanner-2.8
sudo: false
install: true
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar  
  
after_success:
  - mvn clean test jacoco:report coveralls:report       
email:
    on_success: never # default: change
    on_failure: always # default: always

  
addons:
  sonarcloud:
    organization: "pp2-2018" # the key of the org you chose at step #3
    token:
      secure: 9c5cadd46e37c3db60583d778db2ab543cd41bf5

