language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/travis/.sonar/cache
  - $HOME/travis/.sonarscanner/
  - $HOME/.sonarscanner/sonar-scanner-2.8
sudo: false
install: true
  
after_success:
  - mvn clean test jacoco:report coveralls:report     
  
  
email:
    on_success: never # default: change
    on_failure: always # default: always